### ISSUE TITLE
There is already an API for Google Maps on App

### ISSUE THREAD

**Issue by marcusvbp** [deiwin/ngGeolocator#1]
I am creating an App Cordova with Ionic Framework and wish to use the ngGeolocator.

But I'm already using Google Maps API for displaying custom maps. I am getting some error messages:
- "You have included the Google Maps API multiple times on this page This may cause unexpected errors.."

And a lot of:
- "Error: setMap: not an instance of Map; and not an instance of StreetViewPanorama"

I would like to harmonize the use of ngGeolocator with my custom map, or replace my custom map by a ngGeolocator-like option.

Sorry for the bad English.

**Comment by deiwin** [comment]
Hi. Sorry, I didn't see your report until now.

The first errors should be fixed for version 1.0.1, that I just released. (fix is in a76d5ab) Let me know if this also gets rid of the second errors for you. If not, we can look deeper into the issue.

**Comment by deiwin** [comment]
Considering it fixed
